name: NPM packages releaser
on:
  push:
    branches: [main]
  release: 
    types: [published]
  workflow_dispatch:
    inputs:
      package:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Move releaserc config
        run: mv .github/.releaserc npm-packages/x-utils/

      # - name: Edit current directory
      #   run: cd npm-packages/x-utils
      # - name: Use Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "16"
      #     cache: "npm"
      #     registry-url: 'https://npm.pkg.github.com'
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5
          # You can specify specifying version range for the extra plugins if you prefer.
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git
          working_directory: ./npm-packages/x-utils
        env:
          PACKAGE_NAME: x-utils
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}