name: NPM packages releaser
on:
  push:
    branches:
      - main

jobs:
  # matrix strategy to build all packages
  # duplicate the job for each package
  # Action `action-changed-files` watchs for file changes in the package,
  # then trigger a new version
  generate-matrix:
    name: Generate matrix of updated packages
    runs-on: ubuntu-latest
    outputs:
      matrix-npm: ${{ steps.neo-npm.outputs.matrix }}
    steps:
      - name: Generate matrix | Infrastructure
        id: neo-npm
        uses: hellofresh/action-changed-files@v2
        with:
          pattern: npm-packages/(?P<package>(?!.releaserc)[^/]+)

  publish:
    runs-on: ubuntu-22.04
    needs: [generate-matrix]
    strategy:
      max-parallel: 1
      matrix: ${{ fromJson(needs.generate-matrix.outputs.matrix-npm) }}
    if: ${{ fromJson(needs.generate-matrix.outputs.matrix-npm).include[0] }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Move config to current package
        run: |
          mv npm-packages/.releaserc npm-packages/${{ matrix.package }}/

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git
          working_directory: ./npm-packages/${{ matrix.package }}
        env:
          PACKAGE_NAME: ${{ matrix.package }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
