name: NPM packages releaser
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      package:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        # Add an item here when you create a new NPM package
        package:
          - x-utils
          - vtt-parser
          - quizz-parser
          - dependency-injection
    steps:
      - uses: actions/checkout@v3
      - name: Move config to current package
        run: | 
          mv .github/.releaserc npm-packages/${{ matrix.package }}/
          mv .github/.npmrc npm-packages/${{ matrix.package }}/

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install Node dependencies
        run: |
          cd npm-packages/${{ matrix.package }}
          npm ci
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        with:
          semantic_version: 19.0.5
          extra_plugins: |
            @semantic-release/changelog@6.0.1
            @semantic-release/git
          working_directory: ./npm-packages/${{ matrix.package }}
        env:
          PACKAGE_NAME: ${{ matrix.package }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}